name: flutter_sliding_toast
description: "A flutter package for displaying messages with custom styling and animation behavior."
version: 1.5.3
homepage: https://github.com/gaurishankar007/flutter_sliding_toast
repository: https://github.com/gaurishankar007/flutter_sliding_toast
documentation: https://github.com/gaurishankar007/flutter_sliding_toast
issue_tracker: https://github.com/gaurishankar007/flutter_sliding_toast/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  leancode_lint: ^19.0.1
